#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('../app');
var debug = require('debug')('test:server');
var http = require('http');
const dotenv=require("dotenv")
dotenv.config();

/**
 * Get port from environment and store in Express.
 */


/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */


/**
 * Normalize a port into a number, string, or false.
 */



/**
 * Event listener for HTTP server "error" event.
 */



/**
 * Event listener for HTTP server "listening" event.
 */

 app.listen(process.env.PORT||5000,()=>{
  console.log("Server is listening at port",process.env.PORT)
})
